/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-01 09:01:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tw.eeit117.wematch.product.model.ProductBean;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;

public final class VideoPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.5.RELEASE.jar", Long.valueOf(1682903043236L));
    _jspx_dependants.put("/WEB-INF/pages/CSSsettingout.jsp", Long.valueOf(1682928858732L));
    _jspx_dependants.put("/WEB-INF/pages/footerout.jsp", Long.valueOf(1682928858744L));
    _jspx_dependants.put("jar:file:/C:/Users/cheny/Documents/workspace/java/eclipse/eason-eeit117/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WeMatch_dev/WEB-INF/lib/spring-webmvc-5.2.5.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1585020252000L));
    _jspx_dependants.put("/WEB-INF/pages/JSsettingout.jsp", Long.valueOf(1682928858735L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682903035266L));
    _jspx_dependants.put("jar:file:/C:/Users/cheny/Documents/workspace/java/eclipse/eason-eeit117/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WeMatch_dev/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("tw.eeit117.wematch.product.model.ProductBean");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	response.addHeader("x-frame-options", "ALLOW-FROM https://www.youtube.com/");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Video</title>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".notice {\r\n");
      out.write("	color: #ff0000;\r\n");
      out.write("	font-size: small;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#memo {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	color: #ff0000;\r\n");
      out.write("	font-size: small;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	padding-right: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("	display: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3:hover {\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	background: rgba(255, 255, 255, .4);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3:active {\r\n");
      out.write("	background: rgba(255, 255, 255, .8);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".videoTable {\r\n");
      out.write("	color: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filmtopic {\r\n");
      out.write("	color: #0000E3;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uptopic {\r\n");
      out.write("	color: #A23400;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("	text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#intro {\r\n");
      out.write("	color: rgb(255, 255, 255);\r\n");
      out.write("	font-weight: bolder;\r\n");
      out.write("	text-shadow: 3px 3px 3px rgb(0, 0, 0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fixed1 {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	width: 425px;\r\n");
      out.write("	border: 3px solid #9999CC;\r\n");
      out.write("	bottom: 10px;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	margin-right: 30px;\r\n");
      out.write("	display: none;\r\n");
      out.write("	background-color: #F0F0F0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\"\r\n");
      out.write("	data-offset=\"300\">\r\n");
      out.write("	​​​​​​​\r\n");
      out.write("	<nav\r\n");
      out.write("		class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target\"\r\n");
      out.write("		id=\"ftco-navbar\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"/WeMatch_dev/homepage\"\r\n");
      out.write("				style=\"padding-top: 0px;\">Fitness</a>\r\n");
      out.write("			<button class=\"navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle\"\r\n");
      out.write("				type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\"\r\n");
      out.write("				aria-controls=\"ftco-nav\" aria-expanded=\"false\"\r\n");
      out.write("				aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("				<ul class=\"navbar-nav nav ml-auto\">\r\n");
      out.write("					<!-- 				<li class=\"nav-item\"><a href=\"index.html#home-section\" -->\r\n");
      out.write("					<!-- 					class=\"nav-link\"><span>Home</span></a></li> -->\r\n");
      out.write("					<li class=\"nav-item\"><a\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"nav-link\"><span>Products</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						class=\"nav-link\"><span>Courses</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a\r\n");
      out.write("						href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						class=\"nav-link\"><span>Schedule</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						class=\"nav-link\"><span>Diet</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"/WeMatch_dev/video\"\r\n");
      out.write("						class=\"nav-link\"><span>Videoflix</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						class=\"nav-link\"><span>Coach Intro.</span></a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("						class='nav-link'><span>Membership</span></a></li>\r\n");
      out.write("					");

						if ((Map<Integer, List<String>>) session.getAttribute("productArrival") == null) {
						Map<Integer, List<String>> productArrival = new HashMap<Integer, List<String>>();
						session.setAttribute("productArrival", productArrival);
					}
					if ((Set<ProductBean>) session.getAttribute("shoppingCarts") == null) {
						Set<ProductBean> carts = new HashSet<ProductBean>();
						session.setAttribute("shoppingCarts", carts);
					}
					Set<ProductBean> oldCarts = (Set<ProductBean>) session.getAttribute("shoppingCarts");
					out.write("<li class='nav-item'><a href='/WeMatch_dev/shoppingCart/cart' class='nav-link'><span>🛒(" + oldCarts.size()
							+ ")</span></a></li>");
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("					");

						String memberStatus = "" + (Integer) session.getAttribute("Status");
					String memberName = (String) session.getAttribute("memberName");
					if (memberStatus.equals("1") || memberStatus.equals("2")) {
						//out.write("<li class='nav-item'><a href='/WeMatch_dev' class='nav-link'><span>Logout</span></a></li>");
						out.write(
						"<li class='nav-item' style='line-height:16px; margin-top: 0px;'><a href='/WeMatch_dev' class='nav-link'><span style='text-align:center;'><span style='font-style:italic; font-size: 14px; font-weight:bold;'>Welcome,&nbsp;"
								+ memberName + "</span><span>Logout</span></span></a></li>");
					} else {
						out.write("<li class='nav-item'><a href='/WeMatch_dev' class='nav-link'><span>Login</span></a></li>");
					}
					
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<section class=\"hero-wrap hero-wrap-2\"\r\n");
      out.write("		style=\"background-image: url('images/bg_3.jpg');\"\r\n");
      out.write("		data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("		<div class=\"overlay\"></div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"row no-gutters slider-text align-items-end justify-content-center\">\r\n");
      out.write("				<div class=\"col-md-9 ftco-animate pb-5 text-center\">\r\n");
      out.write("					<h1 class=\"mb-3 bread\">Our Stories</h1>\r\n");
      out.write("					<!-- 					<p class=\"breadcrumbs\"> -->\r\n");
      out.write("					<!-- 						<span class=\"mr-2\"><a href=\"index.html\">Home <i -->\r\n");
      out.write("					<!-- 								class=\"ion-ios-arrow-forward\"></i></a></span> <span class=\"mr-2\"><a -->\r\n");
      out.write("					<!-- 							href=\"VideoPage.jsp\">Videoflix <i -->\r\n");
      out.write("					<!-- 								class=\"ion-ios-arrow-forward\"></i></a></span> -->\r\n");
      out.write("					<!-- 					</p> -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"ftco-section ftco-schedule\" id=\"schedule-section\"\r\n");
      out.write("		style=\"padding-bottom: 60px\">\r\n");
      out.write("		<!-- 		<div class=\"container\"> -->\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-md-12 heading-section text-center ftco-animate\">\r\n");
      out.write("			<span class=\"subheading\">Videoflix</span>\r\n");
      out.write("			<h2 class=\"mb-4\">Training Video</h2>\r\n");
      out.write("			<p>No pain, no gain.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- 		</div> -->\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"ftco-section bg-light\" id=\"blog-section\"\r\n");
      out.write("		style=\"padding-top: 50px; padding-bottom: 10px;\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row d-flex\">\r\n");
      out.write("				<div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("					<div class=\"blog-entry justify-content-end\">\r\n");
      out.write("						<img src=\"images/v001.jpg\" class=\"block-20\" style=\"height: 45%;\">\r\n");
      out.write("						<div class=\"text float-right d-block\"\r\n");
      out.write("							style=\"border: grey solid 2px; border-bottom-right-radius: 60px;\">\r\n");
      out.write("							<div class=\"d-flex align-items-center pt-2 mb-4 topp\">\r\n");
      out.write("								<div class=\"one mr-2\">\r\n");
      out.write("									<span class=\"day\" id=\"intro\">背部</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"two\">\r\n");
      out.write("									<span class=\"yr\">&nbsp;</span> <span class=\"mos\"\r\n");
      out.write("										style=\"font-weight: bolder;\">肌群</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3 class=\"heading\" style=\"font-weight: bolder; color: orange\">背部肌群組成與重要性</h3>\r\n");
      out.write("							<p style=\"color: rgb(95, 92, 92);\">核心肌群之一的背部，由多裂肌、豎脊肌、腰方肌等多項肌群組成，當我們站立、起身、前彎時這些肌群就會啟動進行動作，扮演著穩定軀幹的角色。強壯的背部核心肌群不僅能改善一些症狀外同時也能增進在運動上的表現。</p>\r\n");
      out.write("							<div class=\"d-flex align-items-center mt-4 meta\">\r\n");
      out.write("								<p class=\"mb-0\">\r\n");
      out.write("									<a href=\"#v-pills-10-tab\" class=\"btn btn-primary\">Go <span\r\n");
      out.write("										class=\"ion-ios-arrow-round-forward\"></span></a>\r\n");
      out.write("								</p>\r\n");
      out.write("								<p class=\"ml-auto mb-0\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("					<div class=\"blog-entry justify-content-end\">\r\n");
      out.write("						<img src=\"images/v002.jpg\" class=\"block-20\" style=\"height: 45%;\">\r\n");
      out.write("						<div class=\"text float-right d-block\"\r\n");
      out.write("							style=\"border: grey solid 2px; border-bottom-right-radius: 60px;\">\r\n");
      out.write("							<div class=\"d-flex align-items-center pt-2 mb-4 topp\">\r\n");
      out.write("								<div class=\"one mr-2\">\r\n");
      out.write("									<span class=\"day\" id=\"intro\">胸部</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"two\">\r\n");
      out.write("									<span class=\"yr\">&nbsp;</span> <span class=\"mos\"\r\n");
      out.write("										style=\"font-weight: bolder;\">肌群</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3 class=\"heading\" style=\"font-weight: bolder; color: orange\">胸部肌群訓練方式</h3>\r\n");
      out.write("							<p style=\"color: rgb(95, 92, 92);\">胸部肌肉可分為胸大肌、胸小肌和前鋸肌。相對其他部位的肌群而言，胸部肌群要簡單很多，其重點在於對於胸大肌的訓練，常用徒手方法為伏地挺身以及各種變式，負重訓練可採用飛鳥和臥推的方式刺激。</p>\r\n");
      out.write("							<div class=\"d-flex align-items-center mt-4 meta\">\r\n");
      out.write("								<p class=\"mb-0\">\r\n");
      out.write("									<a href=\"#v-pills-10-tab\" class=\"btn btn-primary\">Go <span\r\n");
      out.write("										class=\"ion-ios-arrow-round-forward\"></span></a>\r\n");
      out.write("								</p>\r\n");
      out.write("								<p class=\"ml-auto mb-0\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-4 d-flex ftco-animate\">\r\n");
      out.write("					<div class=\"blog-entry\">\r\n");
      out.write("						<img src=\"images/v003.jpg\" class=\"block-20\" style=\"height: 45%;\">\r\n");
      out.write("						<div class=\"text float-right d-block\"\r\n");
      out.write("							style=\"border: grey solid 2px; border-bottom-right-radius: 60px;\">\r\n");
      out.write("							<div class=\"d-flex align-items-center pt-2 mb-4 topp\">\r\n");
      out.write("								<div class=\"one mr-2\">\r\n");
      out.write("									<span class=\"day\" id=\"intro\">腿部</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"two\">\r\n");
      out.write("									<span class=\"yr\">&nbsp;</span> <span class=\"mos\"\r\n");
      out.write("										style=\"font-weight: bolder;\">肌群</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<h3 class=\"heading\" style=\"font-weight: bolder; color: orange\">強化腿部肌群好處</h3>\r\n");
      out.write("							<p style=\"color: rgb(95, 92, 92);\">大腿主要分為前外側、後側和內側三個肌群。勤練腿部肌群好處相當的多，主要能強化腿部肌群、增強核心肌力、消耗更多的熱量、促進生長激素與睪固酮的濃度、提高新陳代謝等等，因此，腿部肌肉沒練好，幾乎是等於健身無效。</p>\r\n");
      out.write("							<div class=\"d-flex align-items-center mt-4 meta\">\r\n");
      out.write("								<p class=\"mb-0\">\r\n");
      out.write("									<a href=\"#v-pills-10-tab\" class=\"btn btn-primary\">Go <span\r\n");
      out.write("										class=\"ion-ios-arrow-round-forward\"></span></a>\r\n");
      out.write("								</p>\r\n");
      out.write("								<p class=\"ml-auto mb-0\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"ftco-section ftco-schedule\" id=\"schedule-section\"\r\n");
      out.write("		style=\"padding-top: 60px\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- 			<div class=\"row justify-content-center pb-5\"> -->\r\n");
      out.write("			<!-- 				<div class=\"col-md-12 heading-section text-center ftco-animate\"> -->\r\n");
      out.write("			<!-- 					<span class=\"subheading\">Videoflix</span> -->\r\n");
      out.write("			<!-- 					<h2 class=\"mb-4\">Training Video</h2> -->\r\n");
      out.write("			<!-- 					<p>No pain, no gain.</p> -->\r\n");
      out.write("			<!-- 				</div> -->\r\n");
      out.write("			<!-- 			</div> -->\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				<!-- 				<div class=\"coach-wrap ftco-animate d-sm-flex\" -->\r\n");
      out.write("				<!-- 					style=\"padding-top: 10px\"> -->\r\n");
      out.write("				<!-- 					<div>Last Update</div><br> -->\r\n");
      out.write("\r\n");
      out.write("				<!-- 					<div class=\"tab-pane fade show active\" id=\"v-pills-6\" -->\r\n");
      out.write("				<!-- 						role=\"tabpanel\" aria-labelledby=\"day-6-tab\"> -->\r\n");
      out.write("\r\n");
      out.write("				<div class=\"coach-wrap ftco-animate d-sm-flex\"\r\n");
      out.write("					style=\"border-radius: 50px\">\r\n");
      out.write("\r\n");
      out.write("					<table id=contentupdate class=\"updateTable\"\r\n");
      out.write("						style=\"margin-left: 35px\"></table>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 					</div> -->\r\n");
      out.write("				<!-- 				</div> -->\r\n");
      out.write("\r\n");
      out.write("				<!-- 				<div> -->\r\n");
      out.write("				<!-- 					<div class=\"coach-wrap ftco-animate d-sm-flex\" -->\r\n");
      out.write("				<!-- 						style=\"padding-top: 10px\"> -->\r\n");
      out.write("				<!-- 						<h4>Most View</h4> -->\r\n");
      out.write("\r\n");
      out.write("				<!-- 						<div class=\"tab-pane fade show active\" id=\"v-pills-7\" -->\r\n");
      out.write("				<!-- 							role=\"tabpanel\" aria-labelledby=\"day-7-tab\"> -->\r\n");
      out.write("				<!-- 							<div class=\"coach-wrap ftco-animate d-sm-flex\"> -->\r\n");
      out.write("				<!-- 								Show video most view -->\r\n");
      out.write("				<!-- 								<table id=contentview class=\"viewTable\"></table> -->\r\n");
      out.write("				<!-- 							</div> -->\r\n");
      out.write("				<!-- 						</div> -->\r\n");
      out.write("				<!-- 					</div> -->\r\n");
      out.write("				<!-- 				</div> -->\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div id=\"down\"></div>\r\n");
      out.write("			<div class=\"ftco-schedule\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-4 nav-link-wrap\">\r\n");
      out.write("						<div class=\"nav flex-column nav-pills\" id=\"v-pills-tab\"\r\n");
      out.write("							role=\"tablist\" aria-orientation=\"vertical\">\r\n");
      out.write("							<a class=\"nav-link ftco-animate active\" id=\"v-pills-8-tab\"\r\n");
      out.write("								data-toggle=\"pill\" href=\"#v-pills-8\" role=\"tab\"\r\n");
      out.write("								aria-controls=\"v-pills-8\" aria-selected=\"true\">背部肌群 <span>BodyBack,\r\n");
      out.write("									Go go!!</span></a> <a class=\"nav-link ftco-animate\" id=\"v-pills-9-tab\"\r\n");
      out.write("								data-toggle=\"pill\" href=\"#v-pills-9\" role=\"tab\"\r\n");
      out.write("								aria-controls=\"v-pills-9\" aria-selected=\"false\">胸部肌群 <span>Chest,\r\n");
      out.write("									GJ Ha Ha...</span>\r\n");
      out.write("							</a> <a class=\"nav-link ftco-animate\" id=\"v-pills-10-tab\"\r\n");
      out.write("								data-toggle=\"pill\" href=\"#v-pills-10\" role=\"tab\"\r\n");
      out.write("								aria-controls=\"v-pills-10\" aria-selected=\"false\">腿部肌群 <span>Leg,\r\n");
      out.write("									you're leg ker ker...</span>\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<br>\r\n");
      out.write("						<!-- 						<input type=\"button\" value=\"Delete\" -->\r\n");
      out.write("						<!-- 							class=\"btn py-3 px-4 btn-primary\" -->\r\n");
      out.write("						<!-- 							onclick=\"location.href='/WeMatch_dev/VideoDeletePage.jsp'\" -->\r\n");
      out.write("						<!-- 							style=\"float: right; margin-right: 10px;\"> <input -->\r\n");
      out.write("						<!-- 							type=\"button\" value=\"Add\" class=\"btn py-3 px-4 btn-primary\" -->\r\n");
      out.write("						<!-- 							onclick=\"location.href='/WeMatch_dev/VideoListPage.jsp'\" -->\r\n");
      out.write("						<!-- 							style=\"float: right; margin-right: 5px;\"> -->\r\n");
      out.write("\r\n");
      out.write("						<!-- 						<input type=\"button\" value=\"Admin\" -->\r\n");
      out.write("						<!-- 							class=\"btn py-3 px-4 btn-primary\" -->\r\n");
      out.write("						<!-- 							onclick=\"location.href='/WeMatch_dev/VideoDeletePage.jsp'\" -->\r\n");
      out.write("						<!-- 							style=\"float: right; margin-right: 5px;\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("						<!-- 							<input type=\"submit\" value=\"Admin\" -->\r\n");
      out.write("						<!-- 								class=\"btn py-3 px-4 btn-primary\" style=\"float: right\"> -->\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div>\r\n");
      out.write("							");

								if (memberStatus.equals("2")) {
								out.print("<form action='/WeMatch_dev/video/admindelete' method='post'>");
								out.print("<input type='submit' value='Admin' class='btn py-3 px-4 btn-primary' style='float: right'>");
								out.print("</form>");
							} else {
								out.print("<span><input class='btn py-3 px-4 btn-primary' type='button' id='btntest' value='健身影片諮詢室'></span>");
								out.print(
								"<br><br><span style='color:black; font-size:15px;'><span style='font-weight:bold;text-decoration:underline; font-style:italic;'>★健身影片諮詢小提示★</span><br>→&nbsp;想了解三大肌群構造，請輸入\"肌群名稱\"<br>→&nbsp;三大肌群健身風險，請輸入\"肌群名稱+風險\"<br>→&nbsp;健身影片推薦，請輸入\"肌群名稱+級別+推薦\"</span><br><span style='font-weight:bold;color:black; font-size:15px;'>◎&nbsp;Fitness Space感謝您的使用");
							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-8 tab-wrap\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"tab-content\" id=\"v-pills-tabContent\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"tab-pane fade show active\" id=\"v-pills-8\"\r\n");
      out.write("								role=\"tabpanel\" aria-labelledby=\"day-8-tab\">\r\n");
      out.write("								<div class=\"coach-wrap ftco-animate d-sm-flex\">\r\n");
      out.write("									<!--Show Products & Page-->\r\n");
      out.write("									<table id=contentbodyback class=\"videoTable\"></table>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"pageback\" class=\"text-center\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"tab-pane fade\" id=\"v-pills-9\" role=\"tabpanel\"\r\n");
      out.write("								aria-labelledby=\"v-pills-day-9-tab\">\r\n");
      out.write("								<div class=\"coach-wrap ftco-animate d-sm-flex\">\r\n");
      out.write("									<!--Show Products & Page-->\r\n");
      out.write("									<table id=\"contentbodychest\" class=\"videoTable\"></table>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"pagechest\" class=\"text-center\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"tab-pane fade\" id=\"v-pills-10\" role=\"tabpanel\"\r\n");
      out.write("								aria-labelledby=\"v-pills-day-10-tab\">\r\n");
      out.write("								<div class=\"coach-wrap ftco-animate d-sm-flex\">\r\n");
      out.write("									<!--Show Products & Page-->\r\n");
      out.write("									<table id=\"contentbodyleg\" class=\"videoTable\"></table>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"pageleg\" class=\"text-center\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- 健身影音諮詢室Start -->\r\n");
      out.write("	<div class=\"fixed1\" id=\"tt\">\r\n");
      out.write("		<h5 style=\"font-weight: bold; color: blue; padding-top: 8px;\">\r\n");
      out.write("			&nbsp;&nbsp;&nbsp;◆&nbsp;健身影音諮詢室<span><button id=\"cc\"\r\n");
      out.write("					style=\"float: right; margin-right: 15px; margin-bottom: 10px; background-color: #BEBEBE; font-size: 14px; font-weight: bold;\">close</button></span>\r\n");
      out.write("		</h5>\r\n");
      out.write("\r\n");
      out.write("		<!-- 		<button id='btnConn'>開始諮詢</button> -->\r\n");
      out.write("		<!-- 		<span id='status'></span> -->\r\n");
      out.write("		<textarea cols='45' rows='14' id='serverResponseArea'\r\n");
      out.write("			style=\"margin-left: 15px;\" autofocus></textarea>\r\n");
      out.write("		<br> <span\r\n");
      out.write("			style=\"padding-bottom: 8px; font-weight: bold; color: black; margin-left: 15px;\">會員&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("：</span><br>\r\n");
      out.write("		<input type='text' size=\"45\" id='message'\r\n");
      out.write("			style=\"margin-left: 15px; margin-bottom: 10px;\"><br>\r\n");
      out.write("\r\n");
      out.write("		<button id='btnSend' class=\"btn btn-primary\"\r\n");
      out.write("			style=\"margin-left: 15px; margin-bottom: 10px; float: right; margin-right: 15px;\">送出</button>\r\n");
      out.write("		<button id='btnClose' class=\"btn btn-primary\"\r\n");
      out.write("			style=\"margin-left: 10px; margin-bottom: 10px; float: right;\">諮詢結束</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 健身影音諮詢室End -->\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"ftco-footer ftco-section\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row mb-5\">\r\n");
      out.write("			<div class=\"col-md\">\r\n");
      out.write("				<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("					<h2 class=\"ftco-heading-2\">\r\n");
      out.write("						About <span><a href=\"/WeMatch_dev/homepage\">Fitness Space.</a></span>\r\n");
      out.write("					</h2>\r\n");
      out.write("					<p>The gym will always provide the most important tool we need to get through life’s challenge – Perseverance.</p>\r\n");
      out.write("					<p>~From Dwayne Johnson</p>\r\n");
      out.write("<!-- 					<ul -->\r\n");
      out.write("<!-- 						class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-5\"> -->\r\n");
      out.write("<!-- 						<li class=\"ftco-animate\"><a href=\"#\"><span -->\r\n");
      out.write("<!-- 								class=\"icon-twitter\"></span></a></li> -->\r\n");
      out.write("<!-- 						<li class=\"ftco-animate\"><a href=\"#\"><span -->\r\n");
      out.write("<!-- 								class=\"icon-facebook\"></span></a></li> -->\r\n");
      out.write("<!-- 						<li class=\"ftco-animate\"><a href=\"#\"><span -->\r\n");
      out.write("<!-- 								class=\"icon-instagram\"></span></a></li> -->\r\n");
      out.write("<!-- 					</ul> -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("<!-- 			<div class=\"col-md\"> -->\r\n");
      out.write("<!-- 				<div class=\"ftco-footer-widget mb-4 ml-md-4\"> -->\r\n");
      out.write("<!-- 					<h2 class=\"ftco-heading-2\">Links</h2> -->\r\n");
      out.write("<!-- 					<ul class=\"list-unstyled\"> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Home</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>About</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Services</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Cocahes</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Schedule</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Contact</a></li> -->\r\n");
      out.write("<!-- 					</ul> -->\r\n");
      out.write("<!-- 				</div> -->\r\n");
      out.write("<!-- 			</div> -->\r\n");
      out.write("<!-- 			<div class=\"col-md\"> -->\r\n");
      out.write("<!-- 				<div class=\"ftco-footer-widget mb-4\"> -->\r\n");
      out.write("<!-- 					<h2 class=\"ftco-heading-2\">Services</h2> -->\r\n");
      out.write("<!-- 					<ul class=\"list-unstyled\"> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Gym -->\r\n");
      out.write("<!-- 								Fitness</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Crossfit</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Yoa</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Aerobics</a></li> -->\r\n");
      out.write("<!-- 					</ul> -->\r\n");
      out.write("<!-- 				</div> -->\r\n");
      out.write("<!-- 			</div> -->\r\n");
      out.write("			<div class=\"col-md\" style=\"margin-left: 130px;\">\r\n");
      out.write("				<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("					<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("					<div class=\"block-23 mb-3\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><span class=\"icon icon-map-marker\"></span><span\r\n");
      out.write("								class=\"text\">Sec. 2, Heping E. Rd, Taipei 106, Taiwan</span></li>\r\n");
      out.write("							<li><a href=\"#\"><span class=\"icon icon-phone\"></span><span\r\n");
      out.write("									class=\"text\">+886 2 6631 8168</span></a></li>\r\n");
      out.write("							<li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span\r\n");
      out.write("									class=\"text\">fitnessspace@goodsport.com.tw</span></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("				<p>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					Copyright &copy;\r\n");
      out.write("					<script>\r\n");
      out.write("						document.write(new Date().getFullYear());\r\n");
      out.write("					</script>\r\n");
      out.write("					All rights reserved | This template is made with <i\r\n");
      out.write("						class=\"icon-heart color-danger\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("						href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("	<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("			stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("			stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"js/aos.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("<script src=\"js/scrollax.min.js\"></script>\r\n");
      out.write("<!-- 	<script -->\r\n");
      out.write("<!-- 		src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script> -->\r\n");
      out.write("<!-- 	<script src=\"../js/google-map.js\"></script> -->\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"js/jquery-3.2.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"js/VideoUpdate.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"js/VideoPage.js\" type=\"text/javascript\"></script>\r\n");
      out.write("	<script src=\"js/VideoChat.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/pages/VideoPage.jsp(107,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/product/browse");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/pages/VideoPage.jsp(108,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/addCourses");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/pages/VideoPage.jsp(111,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/bookingcontroller/booking");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/pages/VideoPage.jsp(113,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/diet");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/pages/VideoPage.jsp(117,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/coachPage");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/pages/VideoPage.jsp(119,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/MemberPage");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }
}
