/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-05-01 09:01:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import tw.eeit117.wematch.product.model.ProductBean;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;

public final class VideoListPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/pages/headerout.jsp", Long.valueOf(1682928858745L));
    _jspx_dependants.put("/WEB-INF/pages/CSSsettingout.jsp", Long.valueOf(1682928858732L));
    _jspx_dependants.put("/WEB-INF/pages/footerout.jsp", Long.valueOf(1682928858744L));
    _jspx_dependants.put("/WEB-INF/pages/JSsettingout.jsp", Long.valueOf(1682928858735L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682903035266L));
    _jspx_dependants.put("jar:file:/C:/Users/cheny/Documents/workspace/java/eclipse/eason-eeit117/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WeMatch_dev/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("tw.eeit117.wematch.product.model.ProductBean");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Video Check In</title>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".notice {\r\n");
      out.write("	color: #ff0000;\r\n");
      out.write("	font-size: small;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function videokey() {\r\n");
      out.write("		document.getElementById(\"name1\").value = \"胸部基礎訓練1\";\r\n");
      out.write("		document.getElementById(\"category1\").value = \"bodychest\";\r\n");
      out.write("		document.getElementById(\"link1\").value = \"https://www.youtube.com/watch?v=lD0dDIa20DI\";\r\n");
      out.write("		document.getElementById(\"desc1\").value = \"胸部基礎訓練-伏地挺身主要鍛鍊的部位為胸大肌，肱三頭肌，以及核心肌群，而肩部與背部其實也會受惠。準備動作可分兩動：第一動是蹲下使兩手觸地，而第二動為兩手撐地且兩腳向後一瞪。準備動作完成時兩手掌約略在胸口位置。\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\"\r\n");
      out.write("	data-offset=\"300\">\r\n");
      out.write("	​​​​​​​\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<nav\r\n");
      out.write("	class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target\"\r\n");
      out.write("	id=\"ftco-navbar\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"/WeMatch_dev/homepage\"\r\n");
      out.write("			style=\"padding-top: 0px;\">Fitness</a>\r\n");
      out.write("		<button class=\"navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle\"\r\n");
      out.write("			type=\"button\" data-toggle=\"collapse\" data-target=\"#ftco-nav\"\r\n");
      out.write("			aria-controls=\"ftco-nav\" aria-expanded=\"false\"\r\n");
      out.write("			aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("			<ul class=\"navbar-nav nav ml-auto\">\r\n");
      out.write("				<!-- 				<li class=\"nav-item\"><a href=\"index.html#home-section\" -->\r\n");
      out.write("				<!-- 					class=\"nav-link\"><span>Home</span></a></li> -->\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"nav-link\"><span>Products</span></a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("					class=\"nav-link\"><span>Courses</span></a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a\r\n");
      out.write("					href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("					class=\"nav-link\"><span>Schedule</span></a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("					class=\"nav-link\"><span>Diet</span></a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"/WeMatch_dev/video\"\r\n");
      out.write("					class=\"nav-link\"><span>Videoflix</span></a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("					class=\"nav-link\"><span>Coach Intro.</span></a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("					class='nav-link'><span>Membership</span></a></li>\r\n");
      out.write("\r\n");
      out.write("				");

					if ((Map<Integer, List<String>>) session.getAttribute("productArrival") == null) {
					Map<Integer, List<String>> productArrival = new HashMap<Integer, List<String>>();
					session.setAttribute("productArrival", productArrival);
				}
				if ((Set<ProductBean>) session.getAttribute("shoppingCarts") == null) {
					Set<ProductBean> carts = new HashSet<ProductBean>();
					session.setAttribute("shoppingCarts", carts);
				}
				Set<ProductBean> oldCarts = (Set<ProductBean>) session.getAttribute("shoppingCarts");
				out.write("<li class='nav-item'><a href='/WeMatch_dev/shoppingCart/cart' class='nav-link'><span>🛒(" + oldCarts.size()
						+ ")</span></a></li>");
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");

					String memberStatus = "" + (Integer) session.getAttribute("Status");
								String memberName = (String) session.getAttribute("memberName");
								if (memberStatus.equals("1") || memberStatus.equals("2")) {
									//out.write("<li class='nav-item'><a href='/WeMatch_dev' class='nav-link'><span>Logout</span></a></li>");
									out.write(
											"<li class='nav-item' style='line-height:16px; margin-top: 0px;'><a href='/WeMatch_dev' class='nav-link'><span style='text-align:center;'><span style='font-style:italic; font-size: 14px; font-weight:bold;'>Welcome,&nbsp;"
													+ memberName + "</span><span>Logout</span></span></a></li>");
								} else {
									out.write(
											"<li class='nav-item'><a href='/WeMatch_dev' class='nav-link'><span>Login</span></a></li>");
								}
				
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<section class=\"hero-wrap hero-wrap-2\"\r\n");
      out.write("	style=\"background-image: url('images/bg_3.jpg');\"\r\n");
      out.write("	data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("	<div class=\"overlay\"></div>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"row no-gutters slider-text align-items-end justify-content-center\">\r\n");
      out.write("			<div class=\"col-md-9 ftco-animate pb-5 text-center\">\r\n");
      out.write("				<h1 class=\"mb-3 bread\">Our Stories</h1>\r\n");
      out.write("				<!-- 				<p class=\"breadcrumbs\"> -->\r\n");
      out.write("				<!-- 					<span class=\"mr-2\"><a href=\"index.html\">Home <i -->\r\n");
      out.write("				<!-- 							class=\"ion-ios-arrow-forward\"></i></a></span> <span class=\"mr-2\"><a -->\r\n");
      out.write("				<!-- 						href=\"blog.html\">Blog <i class=\"ion-ios-arrow-forward\"></i></a></span> <span>Blog -->\r\n");
      out.write("				<!-- 						Single <i class=\"ion-ios-arrow-forward\"></i> -->\r\n");
      out.write("				<!-- 					</span> -->\r\n");
      out.write("				<!-- 				</p> -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section class=\"ftco-section ftco-schedule\" id=\"schedule-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-center pb-5\">\r\n");
      out.write("				<div class=\"col-md-12 heading-section text-center ftco-animate\">\r\n");
      out.write("					<span class=\"subheading\">Videoflix Check In</span>\r\n");
      out.write("					<h2 class=\"mb-4\">New Training Video</h2>\r\n");
      out.write("					<p>More training, more video.</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"ftco-schedule\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-4 nav-link-wrap\">\r\n");
      out.write("						<div class=\"nav flex-column nav-pills\" id=\"v-pills-tab\"\r\n");
      out.write("							role=\"tablist\" aria-orientation=\"vertical\">\r\n");
      out.write("							<a class=\"nav-link ftco-animate active\" id=\"v-pills-8-tab\"\r\n");
      out.write("								data-toggle=\"pill\" href=\"#v-pills-8\" role=\"tab\"\r\n");
      out.write("								aria-controls=\"v-pills-8\" aria-selected=\"true\">Video\r\n");
      out.write("								Check-in <span>Aloha, new training video!!</span>\r\n");
      out.write("							</a>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-8 tab-wrap\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"tab-content\" id=\"v-pills-tabContent\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"tab-pane fade show active\" id=\"v-pills-8\"\r\n");
      out.write("								role=\"tabpanel\" aria-labelledby=\"day-8-tab\">\r\n");
      out.write("								<div class=\"coach-wrap ftco-animate d-sm-flex\">\r\n");
      out.write("\r\n");
      out.write("									<!--Video Check In Form -->\r\n");
      out.write("									<form action=\"AdminVideoServlet.do\" method=\"get\"\r\n");
      out.write("										enctype=\"multipart/form-data\" class=\"p-5 bg-light\"\r\n");
      out.write("										style=\"position: relative; border: 1px solid black;\">\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<label for=\"videoName\">影片主題</label> <span id=\"namesp\"\r\n");
      out.write("												class=\"notice\"></span><br />\r\n");
      out.write("											<input type=\"text\" id=\"name1\" class=\"form-control\"\r\n");
      out.write("												name=\"videoName\" required=\"required\" autocomplete=\"on\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<label for=\"videoCategory\">影片類別</label><br /> <select\r\n");
      out.write("												name=\"videoCategory\" id=\"category1\">\r\n");
      out.write("												<option value=\"bodyback\">背部肌群訓練</option>\r\n");
      out.write("												<option value=\"bodychest\">胸部肌群訓練</option>\r\n");
      out.write("												<option value=\"bodyleg\">腿部肌群訓練</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<label for=\"videoLink\">影片連結</label> <span id=\"linksp\"\r\n");
      out.write("												class=\"notice\"></span><br /> <input type=\"text\" id=\"link1\"\r\n");
      out.write("												class=\"form-control\" name=\"videoLink\" required=\"required\"\r\n");
      out.write("												autocomplete=\"on\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<label for=\"videoDesc\">影片簡述</label> <span id=\"linksp\"\r\n");
      out.write("												class=\"notice\"></span><br />\r\n");
      out.write("											<!-- 												<input type=\"text\" id=\"desc1\" class=\"form-control\" name=\"videoDesc\"  -->\r\n");
      out.write("											<!-- 												required=\"required\"	autocomplete=\"on\"> -->\r\n");
      out.write("											<textarea name=\"videoDesc\" id=\"desc1\" required=\"required\"\r\n");
      out.write("												style=\"width: 550px; height: 120px;\"></textarea>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<input type=\"submit\" value=\"確認\"\r\n");
      out.write("												class=\"btn py-3 px-4 btn-primary\"> <span><input\r\n");
      out.write("												style=\"position: absolute; right: 0; margin-right: 50px;\"\r\n");
      out.write("												class=\"btn py-3 px-4 btn-primary\" type=\"button\"\r\n");
      out.write("												value=\"Key-in-one\" onclick=\"videokey()\"></span>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div></div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"ftco-footer ftco-section\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row mb-5\">\r\n");
      out.write("			<div class=\"col-md\">\r\n");
      out.write("				<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("					<h2 class=\"ftco-heading-2\">\r\n");
      out.write("						About <span><a href=\"/WeMatch_dev/homepage\">Fitness Space.</a></span>\r\n");
      out.write("					</h2>\r\n");
      out.write("					<p>The gym will always provide the most important tool we need to get through life’s challenge – Perseverance.</p>\r\n");
      out.write("					<p>~From Dwayne Johnson</p>\r\n");
      out.write("<!-- 					<ul -->\r\n");
      out.write("<!-- 						class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-5\"> -->\r\n");
      out.write("<!-- 						<li class=\"ftco-animate\"><a href=\"#\"><span -->\r\n");
      out.write("<!-- 								class=\"icon-twitter\"></span></a></li> -->\r\n");
      out.write("<!-- 						<li class=\"ftco-animate\"><a href=\"#\"><span -->\r\n");
      out.write("<!-- 								class=\"icon-facebook\"></span></a></li> -->\r\n");
      out.write("<!-- 						<li class=\"ftco-animate\"><a href=\"#\"><span -->\r\n");
      out.write("<!-- 								class=\"icon-instagram\"></span></a></li> -->\r\n");
      out.write("<!-- 					</ul> -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("<!-- 			<div class=\"col-md\"> -->\r\n");
      out.write("<!-- 				<div class=\"ftco-footer-widget mb-4 ml-md-4\"> -->\r\n");
      out.write("<!-- 					<h2 class=\"ftco-heading-2\">Links</h2> -->\r\n");
      out.write("<!-- 					<ul class=\"list-unstyled\"> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Home</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>About</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Services</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Cocahes</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Schedule</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Contact</a></li> -->\r\n");
      out.write("<!-- 					</ul> -->\r\n");
      out.write("<!-- 				</div> -->\r\n");
      out.write("<!-- 			</div> -->\r\n");
      out.write("<!-- 			<div class=\"col-md\"> -->\r\n");
      out.write("<!-- 				<div class=\"ftco-footer-widget mb-4\"> -->\r\n");
      out.write("<!-- 					<h2 class=\"ftco-heading-2\">Services</h2> -->\r\n");
      out.write("<!-- 					<ul class=\"list-unstyled\"> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Gym -->\r\n");
      out.write("<!-- 								Fitness</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Crossfit</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Yoa</a></li> -->\r\n");
      out.write("<!-- 						<li><a href=\"#\"><span class=\"icon-long-arrow-right mr-2\"></span>Aerobics</a></li> -->\r\n");
      out.write("<!-- 					</ul> -->\r\n");
      out.write("<!-- 				</div> -->\r\n");
      out.write("<!-- 			</div> -->\r\n");
      out.write("			<div class=\"col-md\" style=\"margin-left: 130px;\">\r\n");
      out.write("				<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("					<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("					<div class=\"block-23 mb-3\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><span class=\"icon icon-map-marker\"></span><span\r\n");
      out.write("								class=\"text\">Sec. 2, Heping E. Rd, Taipei 106, Taiwan</span></li>\r\n");
      out.write("							<li><a href=\"#\"><span class=\"icon icon-phone\"></span><span\r\n");
      out.write("									class=\"text\">+886 2 6631 8168</span></a></li>\r\n");
      out.write("							<li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span\r\n");
      out.write("									class=\"text\">fitnessspace@goodsport.com.tw</span></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("				<p>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					Copyright &copy;\r\n");
      out.write("					<script>\r\n");
      out.write("						document.write(new Date().getFullYear());\r\n");
      out.write("					</script>\r\n");
      out.write("					All rights reserved | This template is made with <i\r\n");
      out.write("						class=\"icon-heart color-danger\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("						href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("	<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("			stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("			stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"js/aos.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("<script src=\"js/scrollax.min.js\"></script>\r\n");
      out.write("<!-- 	<script -->\r\n");
      out.write("<!-- 		src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script> -->\r\n");
      out.write("<!-- 	<script src=\"../js/google-map.js\"></script> -->\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/pages/headerout.jsp(30,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/product/browse");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/pages/headerout.jsp(31,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/addCourses");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/pages/headerout.jsp(34,11) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/bookingcontroller/booking");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/pages/headerout.jsp(36,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/diet");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/pages/headerout.jsp(40,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/coachPage");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/pages/headerout.jsp(42,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/MemberPage");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }
}
